version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: efca_db
    ports:
    - 5444:5432
    environment:
      POSTGRES_DB: efca
      POSTGRES_USER: efca
      POSTGRES_PASSWORD: efca
  redis:
    image: redis:latest
    restart: always
    container_name: efca_redis
    ports:
    - 6377:6379
  mongo:
    image: mongo:latest
    restart: always
    container_name: efca_mongo
    ports:
    - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: efca
      MONGO_INITDB_ROOT_PASSWORD: efca