version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: efca_db
    ports:
    - 5444:5432
    environment:
      POSTGRES_DB: efca
      POSTGRES_USER: efca
      POSTGRES_PASSWORD: efca