logging.level.org.springframework.data.r2dbc: DEBUG
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5444/efca
    username: efca
    password: efca
  liquibase:
    url: jdbc:postgresql://localhost:5444/efca
    user: efca
    password: efca
    change-log: classpath:db/changelog/db.changelog-master.xml
  redis:
    host: localhost
    port: 6377
  data:
    mongodb:
      host: localhost
      port: 27018
      username: efca
      password: efca
